image: gitpod/workspace-postgres

tasks:
    - name: run back-end
      openMode: split-left
      init: npm install
      command: npm start

    - name: run front-end
      init: cd client && npm install
      command: |
          echo "REACT_APP_API_URL=$(gitpod url 3001)" > .env
          npm start
      openMode: split-right