tasks:
    hello:
        name: Hello World
        command: |
            echo "Hello, World!"
        triggeredBy:
        - manual
        # - postEnvironmentStart
        # - postDevcontainerStart

services:
    backend:
        name: Backend Service
        description: Example service simulating a backend
        commands:
            start: |
                npm install pg dotenv
                npm install
                npm start
            # stop: |
            # 	echo "Stopping backend service..."
            # 	rm /tmp/backend.started
            # 	pkill backend
        triggeredBy:
            - postEnvironmentStart
            # - postDevcontainerStart

